---
controllers:
  resource:
    path: ../src/Controller/
    namespace: XpTracker\Controller
  type: attribute

api_character_create:
  path: /api/character
  controller: XpTracker\Character\Infrastructure\Entrypoint\Api\PostAddCharacterController

api_party_create:
  path: /api/party
  controller: XpTracker\Character\Infrastructure\Entrypoint\Api\PostCreatePartyController
