---
services:
  _defaults:
    autowire: true
    autoconfigure: true
  XpTracker\Tests\Acceptance\:
    resource: '../tests/Acceptance/*'
  XpTracker\Character\Infrastructure\Persistence\DbalAddCharacterWriteModel:
    public: true
  XpTracker\Character\Infrastructure\Persistence\EventStoreCharacterRepository:
    public: true
