---
parameters:
services:
  _defaults:
    autowire: true
    autoconfigure: true
  XpTracket\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
