---
parameters:
services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $commandBus: '@command.bus'
      $eventAsyncBus: '@event.async.bus'
  _instanceof:
    XpTracker\Shared\Application\CommandHandlerInterface:
      tags:
        - {name: messenger.message_handler, bus: command.bus}
    XpTracker\Shared\Application\EventHandlerInterface:
      tags:
        - {name: messenger.message_handler, bus: event.async.bus}
  XpTracker\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
