---
jms_serializer:
  visitors:
    xml_serialization:
      format_output: '%kernel.debug%'
  metadata:
    directories:
      party:
        namespace_prefix: "XpTracker\\Encounter\\Domain"
        path: "%kernel.project_dir%/src/Encounter/Infrastructure/Serializer"

when@prod:
  jms_serializer:
    visitors:
      json_serialization:
        options:
          - JSON_UNESCAPED_SLASHES
          - JSON_PRESERVE_ZERO_FRACTION
when@dev:
  jms_serializer:
    visitors:
      json_serialization:
        options:
          - JSON_PRETTY_PRINT
          - JSON_UNESCAPED_SLASHES
          - JSON_PRESERVE_ZERO_FRACTION
