POST http://localhost:5000/api/character
Content-Type: application/json

{
  "id": "01HJCGHACDM5XTZVCECF88N2KZ",
  "characterName": "Darling",
  "experiencePoints": 300
}

POST http://localhost:5000/api/character
Content-Type: application/json

{
  "characterName": "Darling",
  "experiencePoints": 300
}
